### ISSUE TITLE
Bump up brew formula

### ISSUE THREAD

**Issue by eed3si9n** [foundweekends/giter8#210]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/giter8.rb

**Comment by ilovezfs** [comment]
@eed3si9n I've bumped the formula and restructured it to use your conscript tool so that it actually installs everything, as well as added bottling support: https://github.com/Homebrew/homebrew-core/pull/4205

I just shipped it :) Please let me know if you'd like any tweaks.

**Comment by eed3si9n** [comment]
This is awesome. Thanks for your help!

**Comment by eed3si9n** [comment]
@ilovezfs Is conscript on Homebrew? It might be convenient if ppl can install conscript via Homebrew and then this formula can that to install Giter8.

**Comment by ilovezfs** [comment]
@eed3si9n you're welcome! A couple things that would be helpful:

1. an `--offline` option to pass to your setup script so that it knows not to run wget (and so that the formula doesn't have to do string replacements on it to achieve that goal)
2. do you know if there is a way to (even temporarily?) relocate the sbt lock file so that it's somewhere writable during the test so that the full libexec directory doesn't need to be copied?

conscript is not currently in Homebrew, but that sounds useful regardless of whether it's used with the giter8 formula or not.

If it's actually going to be used by the giter8 formula, the difficult part as always is likely to be coming up with a design that plays nicely with the macOS sandboxes that we use during the build (and during the test). Or from another standpoint, where do you want the installed files to end up? What paths need to be writable during build time and run time for that to happen?

**Comment by eed3si9n** [comment]
I'm fine with adding `--offline` option to conscript setup script. Feel free to open an issue or PR to conscript.
The lock file is created to protect the `boot` directory, where Ivy will cache the downloaded artifacts, so if you want to test something I'm guessing you could set CONSCRIPT_HOME to some temp directory. Note that the location of boot directory will be stored in `$CONSCRIPT_HOME/foundweekends/giter8/g8/launchconfig`.

Conscript is currently designed to install all apps under `~/.conscript/` with each shell script put under `~/.conscript/bin/`. I think it would be fine to have an option where apps are installed with the convention used by Homebrew like:

- app-version created under `/usr/local/Celler/foo/0.1.0/`
- shell script goes to `/usr/local/Celler/foo/0.1.0/bin`
- each app-version has its own boot directory under `libexec`.
