### ISSUE TITLE
Mention make-it-g8 in the documentation

### ISSUE THREAD

**Issue by arturopala** [foundweekends/giter8#450]
Hi, https://github.com/arturopala/make-it-g8 is a scala tool to quickly convert any project into giter8 template. I think it would make sense to add a link to the documentation.

**Comment by arturopala** [comment]
Hi @xuwei-k, what do you think about my

**Comment by arturopala** [comment]
Hi @eed3si9n, what do you think about my tool https://github.com/arturopala/make-it-g8 ?

**Comment by eed3si9n** [comment]
I feel like it would be somewhat hypocritical if `sbt new foundweekends/giter8.g8` didn't work well enough :)

I don't have opinion on make-it-g8 since I've never used it. Looking at the example linked from the repo https://github.com/hmrc/template-play-27-frontend-fsm.g8/blob/21936c330ee5e2d90a869e42eefa1f5cbbc6d25d/src/main/g8/default.properties makes me question if that's an ideal template that a human would write though. For me, at least, a template with 100 parameters does not make sense.

Having said that, if you or others are enthusiastic about that style of templates, I'd be happy to let you advertise your tool.

**Comment by arturopala** [comment]
Thanks, @eed3si9n for your answer. Skipping parameter if unused in the template is from now in my backlog.
