### ISSUE TITLE
intermittent test failures in community build (Format, StableVersion)

### ISSUE THREAD

**Issue by SethTisue** [foundweekends/giter8#455]
example of `Format.formatLowercase` failing (sometimes it's `Format.formatUppercase` that fails instead):

* Format.formatLowercase

example of StableVersion failing: 

* https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3046/artifact/logs/giter8-build.log

they fail only intermittently, but pretty commonly, or I wouldn't be here filing the bug

I will exclude the tests from the community build. (I can re-enable them on request, if a fix is believed to have been found.)

**Comment by TonioGela** [comment]
I just debugged a bit and what I discovered is that the 2 tests fail when the first argument is `i`

For some reason, the whole Antlr String template fails to instantiate when you define a variable as `$i$` and so does giter8

The stack trace is
```
org.stringtemplate.v4.compiler.STException: 1:1: implicitly-defined attribute i not visible
	at giter8.G8$STErrorHandler.compileTimeError(g8.scala:162)
	at giter8.G8$STErrorHandler.compileTimeError(g8.scala:160)
	at org.stringtemplate.v4.misc.ErrorManager.compileTimeError(ErrorManager.java:82)
	at org.stringtemplate.v4.compiler.CompilationState.refAttr(CompilationState.java:75)
	at org.stringtemplate.v4.compiler.CodeGenerator.refAttr(CodeGenerator.java:183)
	at org.stringtemplate.v4.compiler.CodeGenerator.primary(CodeGenerator.java:1923)
	at org.stringtemplate.v4.compiler.CodeGenerator.includeExpr(CodeGenerator.java:1830)
	at org.stringtemplate.v4.compiler.CodeGenerator.expr(CodeGenerator.java:1440)
	at org.stringtemplate.v4.compiler.CodeGenerator.exprElement(CodeGenerator.java:633)
	at org.stringtemplate.v4.compiler.CodeGenerator.singleElement(CodeGenerator.java:528)
	at org.stringtemplate.v4.compiler.CodeGenerator.element(CodeGenerator.java:473)
	at org.stringtemplate.v4.compiler.CodeGenerator.chunk(CodeGenerator.java:300)
	at org.stringtemplate.v4.compiler.CodeGenerator.template(CodeGenerator.java:255)
	at org.stringtemplate.v4.compiler.Compiler.compile(Compiler.java:170)
	at org.stringtemplate.v4.STGroup.compile(STGroup.java:514)
	at giter8.G8$.applyTemplate(g8.scala:136)
```

It happens when `ST` is built [in applyTemplate](https://github.com/foundweekends/giter8/blob/develop/library/src/main/scala/g8.scala#L134), in particular, that constructors is defined as

```
public ST(STGroup group, String template) {
        this();
        groupThatCreatedThisInstance = group;
        impl = groupThatCreatedThisInstance.compile(group.getFileName(), null,
                                                    null, template, null);
        impl.hasFormalArgs = false;
        impl.name = UNKNOWN_NAME;
        impl.defineImplicitlyDefinedTemplates(groupThatCreatedThisInstance);
    }
```
and what throws is the `groupThatCreatedThisInstance.compile` step.

I'll further investigate. As a workaround, we can trick the generators to avoid creating an `i` as a variable but it seems pointless to me.

**Comment by TonioGela** [comment]
Following the calls I found that the `groupThatCreatedThisInstance.compile` calls [this line](https://github.com/antlr/stringtemplate4/blob/master/src/org/stringtemplate/v4/STGroup.java#L514) and then it calls the [template](https://github.com/antlr/stringtemplate4/blob/master/src/org/stringtemplate/v4/compiler/Compiler.java#L170) method.
The template method that gets generated for java contains an `if` that is generated from [these lines](https://github.com/antlr/stringtemplate4/blob/master/src/org/stringtemplate/v4/compiler/CodeGenerator.g#L153-L154) that warned me since it seems that `i` and `i0` are considered formal arguments by default by ST (and that in case of subtemplates are inserted by default, not our case).
Apparently is not possible to use `i` and `i0` as variables, so each property-based tests that try to test the template using one of the 2 var names will fail (and so will giter8)
```scala
  property("plainBrokenConversion")   = { conversion("$i$", Map("i" -> "k")) == "k" }
  property("plainBrokenConversion0")  = { conversion("$i0$", Map("i0" -> "k")) == "k" }
  property("plainWorkingConversion")  = { conversion("$I$", Map("I" -> "k")) == "k" }
  property("plainWorkingConversion0") = { conversion("$I0$", Map("I0" -> "k")) == "k" }
```
The first 2 tests will break while the last 2 will work flawlessly.

One of the problems now is that it is impossible to manually impose that our template is a subtemplate (setting "_sub" as name will be enough) because constructors are not public.

A possible workaround that will solve both flaky tests and enable `i` and `i0` usage is to intercept the strings `$i$` and `$i0$` and to alter both the `defaultString`, both the [attributes](https://github.com/foundweekends/giter8/blob/develop/library/src/main/scala/g8.scala#L131).
I'll do some tests to check whether this solution works.

**Comment by TonioGela** [comment]
Like any good developer, I coded for hours to avoid reading documentation.
In fact `i` and `i0` are reserved expression/keywords as confirmed by [documentation](https://github.com/antlr/stringtemplate4/blob/master/doc/cheatsheet.md).

`i` and `i0` are the easiest expressions to generate for `Gen`, but the tests were flaky since in 100 iterations is not obvious that one of the two gets generated.
I modified the generators to avoid creating the following tokens:
```scala
lazy val prohibited_variable_names: List[String] = List(
  "i",
  "i0",
  "if",
  "else",
  "elseif",
  "endif",
  "first",
  "length",
  "strlen",
  "last",
  "rest",
  "reverse",
  "trunc",
  "strip",
  "trim"
)
```
and I used the very same list to test that these are in fact prohibited:
```scala
prohibited_variable_names.map(x => property(s"$x is prohibited") = throws(s"$dollar$x$dollar", Map.empty))
```
I added to `build.sbt` the following setting:
```scala
Test / testOptions += Tests.Argument(TestFrameworks.ScalaCheck, "-minSuccessfulTests", "1000", "-workers", "10")
```
to have 10 times the tests we had before: if it has to fail, at least we'll spot sooner the problem, and the CI time won't grow so much.
There are probably other prohibited tokens, but I added all the ones that I've been able to verify.
I will add these tokens in documentation asap.

**Comment by TonioGela** [comment]
@SethTisue the test should not be flakier now. If you want, you can try to read giter8 to community builds now ;)

**Comment by SethTisue** [comment]
@TonioGela trying it at https://github.com/scala/community-build/pull/1424

**Comment by TonioGela** [comment]
Atm I see a 404 on the builds page on typesafe.com but I'll wait for your feedback here

**Comment by SethTisue** [comment]
@TonioGela I've merged the PR. time will tell whether the intermittent failures return, but if you don't hear back from me can you assume they went away :-)

**Comment by TonioGela** [comment]
Awesome, thanks ;)
