### ISSUE TITLE
'skip_folder' being generated

### ISSUE THREAD

**Issue by kgyokov** [foundweekends/giter8#478]
## steps

Create a folder in a giter8 template:

<pre>
src/main/g8/src/main/scala/$package__packaged$/mycode/$if(my_option.truthy)$.$else$skip_folder$endif$
     |
     --------Myfile.scala
</pre>

Run sbt with **--my_option=false**

Observe that there is a 'skip_folder' created with Myfile.scala in it

sbt or Giter8 version: sbt 1.4.2

## problem

<details>
Seems to work correctly when I swap the places of '.' and  'skip_folder':

<pre>
src/main/g8/src/main/scala/$package__packaged$/mycode/$if(my_option.truthy)$skip_folder$else$.$endif$
     |
     -------- myfile.scala
</pre>

</details>

## expectation

It is my understanding that 'skip_folder' is just a keyword and should never be included as an actual folder, whether it is in the 'true' branch or in the 'false' branch

**Comment by kgyokov** [comment]
Didn't realize `$if(my_option.truthy)$.$endif$` would work (I thought 'skip_folder' is always required to ignore the contents). So this is a very low-priority bug, but I think it would probably be nice if the behavior of 'skip_folder' is consistent

**Comment by TonioGela** [comment]
I imagine you probably took the `skip_folder` name in the example in [the conditionals section of the documentation](http://www.foundweekends.org/giter8/template.html#Conditionals):

The documentation states:
>If you want to skip a directory from the path, but keep all nested directories and files, use . as the name of the directory.

To the best of my understanding, if you use a condition like the one you posted

```
foo/$if(my_option.truthy)$.$else$wrapping_folder$endif$/bar.scala
```

the outcome according to the value of `my_option` will be:

```
true  => foo/bar.scala
false => foo/wrapping_folder/bar.scala
```

Probably (and I'm saying that since I haven't written it), `skip_folder` is just an unhappy name.

I just tested it with a different name (`box`) and it works as expected, given this folder name:
![image](https://user-images.githubusercontent.com/41690956/118941921-897c1780-b952-11eb-8920-b2d240a9f7a9.png)
If I create it using `unbox=false` I get:
![image](https://user-images.githubusercontent.com/41690956/118942065-aca6c700-b952-11eb-9e78-e512c63191f2.png)
While with `unbox=true` I get:
![image](https://user-images.githubusercontent.com/41690956/118942195-c942ff00-b952-11eb-988b-310b6cb3d220.png)

Does this answers your question @kgyokov?

**Comment by TonioGela** [comment]
@eed3si9n I think this one can be closed unless @kgyokov disagrees.
